import axios from 'axios';
import Head from 'next/head';
import About from '../components/About/About';
import BlogCom from '../components/BlogCom/BlogCom';
import Counter from '../components/Counter/Counter';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';
import Provide from '../components/Provide/Provide';
import Review from '../components/Reviews/Review';
import TeamDetails from '../components/TeamDetails/TeamDetails';
import WhyUs from '../components/WhyUs/WhyUs';

export default function Home({ BLOG_DATA }) {
    return (
        <div className="container">
            <Head>
                <title>Techvi</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="main">
                <Header />
                <Provide />
                <About />
                <WhyUs />
                <Counter />
                <Review />
                <TeamDetails />
                <BlogCom blogDetails={BLOG_DATA} />
                <Footer />
            </main>
        </div>
    );
}

export async function getStaticProps() {
    const res = await axios.get('http://localhost:4000/api/blog');
    const dataMain = await res.data.message;
    return {
        props: {
            BLOG_DATA: dataMain,
        },
    };
}
