import Head from 'next/head'
import About from '../components/About/About'
import Counter from '../components/Counter/Counter'
import Header from '../components/Header/Header'
import Provide from '../components/Provide/Provide'
import WhyUs from '../components/WhyUs/WhyUs'

export default function Home() {
  return (
    <div className={"container"}>
      <Head>
        <title>Techvi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"main"}>
        <Header />
        <Provide />
        <About />
        <WhyUs />
        <Counter />
      </main>
    </div>
  )
}
